// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO01KnRxJy9dFxCwvG4PrkEoEQGDvUyx8',
    appId: '1:625583687267:web:02e60194e37134ad1b1a56',
    messagingSenderId: '625583687267',
    projectId: 'nbaafrica',
    authDomain: 'nbaafrica.firebaseapp.com',
    storageBucket: 'nbaafrica.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnHDjqLCtJAg4crrtCPcDIlKMsuoINihg',
    appId: '1:625583687267:android:9dbf159ca94413431b1a56',
    messagingSenderId: '625583687267',
    projectId: 'nbaafrica',
    storageBucket: 'nbaafrica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuWv9NjxOM8dZlK8jUKMKx7IIWohcYisg',
    appId: '1:625583687267:ios:a6aa72bf521ba1991b1a56',
    messagingSenderId: '625583687267',
    projectId: 'nbaafrica',
    storageBucket: 'nbaafrica.firebasestorage.app',
    iosBundleId: 'com.example.nbaafrica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuWv9NjxOM8dZlK8jUKMKx7IIWohcYisg',
    appId: '1:625583687267:ios:a6aa72bf521ba1991b1a56',
    messagingSenderId: '625583687267',
    projectId: 'nbaafrica',
    storageBucket: 'nbaafrica.firebasestorage.app',
    iosBundleId: 'com.example.nbaafrica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO01KnRxJy9dFxCwvG4PrkEoEQGDvUyx8',
    appId: '1:625583687267:web:4d3c18a0678929ae1b1a56',
    messagingSenderId: '625583687267',
    projectId: 'nbaafrica',
    authDomain: 'nbaafrica.firebaseapp.com',
    storageBucket: 'nbaafrica.firebasestorage.app',
  );

}